import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


ROOT = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(ROOT, "Nature_Preprint_Realtime_NVQLink_SSS.pdf")
PLOT_OUTPUT = os.path.join(ROOT, "realtime_nvqlink_sss_plots.png")


def make_plots(filename=PLOT_OUTPUT):
    frames = np.arange(120)
    time = frames / 119.0
    internal = 0.78 + 0.08 * np.sin(2 * np.pi * 3 * time)
    external = 0.34 + 0.20 * np.sin(2 * np.pi * 14 * time) + 0.06 * np.cos(2 * np.pi * 31 * time)
    residual = np.abs(0.06 * np.sin(2 * np.pi * 5 * time) + 0.02 * np.cos(2 * np.pi * 21 * time))
    latency_ms = 3.5 + 0.8 * np.exp(-5 * time) + 0.25 * np.sin(2 * np.pi * 8 * time)

    figure, axes = plt.subplots(2, 2, figsize=(7.1, 5.8), constrained_layout=True)
    axes[0, 0].plot(time, internal, color="#1f5f8b", linewidth=1.8, label="Internal component")
    axes[0, 0].plot(time, external, color="#b23a48", linewidth=1.4, label="External component")
    axes[0, 0].set_title("SSS component separation", loc="left", fontsize=10, fontweight="bold")
    axes[0, 0].set_xlabel("Window time")
    axes[0, 0].set_ylabel("Relative field")
    axes[0, 0].legend(frameon=False, fontsize=8)

    axes[0, 1].plot(time, residual, color="#6a4c93", linewidth=1.8)
    axes[0, 1].fill_between(time, residual, color="#c8b8dc", alpha=0.55)
    axes[0, 1].set_title("Reconstruction residual", loc="left", fontsize=10, fontweight="bold")
    axes[0, 1].set_xlabel("Window time")
    axes[0, 1].set_ylabel("||y - y_hat||")

    axes[1, 0].plot(time, latency_ms, color="#d17a22", linewidth=1.8)
    axes[1, 0].axhline(5.0, color="#333333", linestyle="--", linewidth=1, label="5 ms budget")
    axes[1, 0].set_title("Realtime processing latency", loc="left", fontsize=10, fontweight="bold")
    axes[1, 0].set_xlabel("Window time")
    axes[1, 0].set_ylabel("Latency (ms)")
    axes[1, 0].legend(frameon=False, fontsize=8)

    orders = [1, 2, 3, 4, 5, 6, 7, 8]
    internal_modes = [2 * order + 1 for order in orders]
    external_modes = [2 * order + 1 for order in orders]
    axes[1, 1].plot(orders, np.cumsum(internal_modes), marker="o", color="#1f5f8b", label="Internal modes")
    axes[1, 1].plot(orders, np.cumsum(external_modes), marker="s", color="#b23a48", label="External modes")
    axes[1, 1].set_title("Finite spherical-harmonic basis", loc="left", fontsize=10, fontweight="bold")
    axes[1, 1].set_xlabel("Maximum order L")
    axes[1, 1].set_ylabel("Modes through order L")
    axes[1, 1].legend(frameon=False, fontsize=8)
    for axis in axes.flat:
        axis.grid(True, alpha=0.18)
        axis.spines["top"].set_visible(False)
        axis.spines["right"].set_visible(False)
    figure.savefig(filename, dpi=180, bbox_inches="tight")
    plt.close(figure)
    return filename


def build_pdf(filename=OUTPUT):
    plot_filename = make_plots()
    doc = SimpleDocTemplate(filename, pagesize=letter, rightMargin=0.72 * inch, leftMargin=0.72 * inch,
                             topMargin=0.65 * inch, bottomMargin=0.65 * inch,
                             title="Realtime NVQLink Signal Space Separation", author="Neuromorph MEG/MRI Hybrid Simulation Group")
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="PaperTitle", parent=styles["Title"], alignment=TA_CENTER, fontName="Helvetica-Bold", fontSize=17, leading=21, spaceAfter=5))
    styles.add(ParagraphStyle(name="Subtitle", parent=styles["Normal"], alignment=TA_CENTER, fontName="Helvetica-Oblique", fontSize=10, leading=13, textColor=colors.HexColor("#404040")))
    styles.add(ParagraphStyle(name="BodyJustified", parent=styles["BodyText"], alignment=TA_JUSTIFY, fontName="Times-Roman", fontSize=10.3, leading=14, spaceAfter=7))
    styles.add(ParagraphStyle(name="Equation", parent=styles["Normal"], alignment=TA_CENTER, fontName="Helvetica-Oblique", fontSize=10.7, leading=16, spaceBefore=4, spaceAfter=8))
    styles.add(ParagraphStyle(name="Small", parent=styles["Normal"], fontName="Times-Roman", fontSize=8.7, leading=11))

    story = [
        Paragraph("Realtime NVQLink Signal Space Separation for MEG", styles["PaperTitle"]),
        Paragraph("A finite spherical-harmonic pipeline for internal-field reconstruction and external-noise monitoring", styles["Subtitle"]),
        Spacer(1, 10),
        Paragraph("<b>Abstract.</b> Realtime MEG processing must suppress environmental interference without erasing the internal field generated by neural currents. We describe a finite NVQLink-style processing loop based on signal space separation (SSS), Tikhonov regularization and a continued-fraction-compatible radial decay term. The implementation uses internal order L<sub>in</sub> = 4, external order L<sub>out</sub> = 3 and a bounded streaming window. The plots and equations define a computational preprint protocol; they do not establish clinical performance or hardware timing on a deployed NVQLink system.", styles["BodyJustified"]),
        Paragraph("1. Finite streaming measurement model", styles["Heading2"]),
        Paragraph("For M sensors and W samples in one processing window, let Y in C^(M x W) contain the measured field. The observation is decomposed into internal neural field, external interference and sensor noise:", styles["BodyJustified"]),
        Paragraph("Y = S<sub>in</sub>A<sub>in</sub> + S<sub>out</sub>A<sub>out</sub> + N, &nbsp; S<sub>in</sub> in C<sup>M x K<sub>in</sub></sup>, &nbsp; S<sub>out</sub> in C<sup>M x K<sub>out</sub></sup>.", styles["Equation"]),
        Paragraph("For spherical-harmonic order L, the number of modes is K(L) = sum<sub>l=1</sub><sup>L</sup>(2l + 1) = L(L + 2). Thus K<sub>in</sub> = K(4) = 24, K<sub>out</sub> = K(3) = 15, and the combined design matrix has 39 columns. These fixed dimensions make each window's least-squares problem finite and auditable.", styles["BodyJustified"]),
        Paragraph("2. Spherical-harmonic SSS basis", styles["Heading2"]),
        Paragraph("For sensor m at spherical coordinates (r<sub>m</sub>, theta<sub>m</sub>, phi<sub>m</sub>), the internal and external basis functions are:", styles["BodyJustified"]),
        Paragraph("S<sub>in,lm</sub>(m) = r<sub>m</sub><sup>l</sup>Y<sub>lm</sub>(theta<sub>m</sub>,phi<sub>m</sub>), &nbsp; S<sub>out,lm</sub>(m) = r<sub>m</sub><sup>-(l+1)</sup>Y<sub>lm</sub>(theta<sub>m</sub>,phi<sub>m</sub>), &nbsp; 1 &le; l &le; L.", styles["Equation"]),
        Paragraph("The external radial factor can be evaluated with a finite continued-fraction recurrence. For x = 1/r and order l, f<sub>l</sub>(x) = x<sup>l+1</sup>; a stabilized implementation may instead update f<sub>l+1</sub> = x f<sub>l</sub> with an origin cutoff r &ge; 10<sup>-3</sup>. This preserves the intended radial decay while avoiding a singular numerical evaluation.", styles["BodyJustified"]),
        Paragraph("3. Regularized separation and realtime update", styles["Heading2"]),
        Paragraph("Let S = [S<sub>in</sub> | S<sub>out</sub>] and lambda > 0. The Tikhonov coefficients for one window are:", styles["BodyJustified"]),
        Paragraph("A&#770; = (S<sup>*</sup>S + &lambda; I)<sup>-1</sup>S<sup>*</sup>Y, &nbsp; Y&#770;<sub>in</sub> = S<sub>in</sub>A&#770;<sub>in</sub>, &nbsp; Y&#770;<sub>out</sub> = S<sub>out</sub>A&#770;<sub>out</sub>.", styles["Equation"]),
        Paragraph("An NVQLink-style streaming loop processes q = 0,...,Q-1 windows and carries a bounded state h<sub>q</sub> containing the previous coefficient estimate. With 0 &le; rho &lt; 1:", styles["BodyJustified"]),
        Paragraph("h<sub>q+1</sub> = &rho;h<sub>q</sub> + (1 - &rho;)A&#770;<sub>q</sub>, &nbsp; q = 0,...,Q-1; &nbsp; Y&#770;<sub>q,in</sub> = S<sub>in</sub>h<sub>q,in</sub>.", styles["Equation"]),
        Paragraph("The internal output is the signal passed downstream; the external output is retained as a noise-monitoring channel. A finite quality measure is e<sub>q</sub> = ||Y<sub>q</sub> - Y&#770;<sub>q,in</sub> - Y&#770;<sub>q,out</sub>||<sub>F</sub>/||Y<sub>q</sub>||<sub>F</sub>.", styles["BodyJustified"]),
        Paragraph("4. Realtime characteristics", styles["Heading2"]),
        Image(plot_filename, width=6.65 * inch, height=5.45 * inch),
        Paragraph("<b>Figure 1.</b> Deterministic finite examples of internal/external SSS separation, reconstruction residual, per-window latency and cumulative spherical-harmonic mode count.", styles["Small"]),
    ]

    characteristics = [
        [Paragraph("Characteristic", styles["Small"]), Paragraph("Finite setting", styles["Small"]), Paragraph("Interpretation", styles["Small"])],
        [Paragraph("Internal basis", styles["Small"]), Paragraph("L<sub>in</sub> = 4; K<sub>in</sub> = 24", styles["Small"]), Paragraph("Neural/internal field subspace", styles["Small"])],
        [Paragraph("External basis", styles["Small"]), Paragraph("L<sub>out</sub> = 3; K<sub>out</sub> = 15", styles["Small"]), Paragraph("Environmental interference subspace", styles["Small"])],
        [Paragraph("Regularization", styles["Small"]), Paragraph("lambda > 0; fixed per window", styles["Small"]), Paragraph("Controls ill-conditioning", styles["Small"])],
        [Paragraph("Streaming state", styles["Small"]), Paragraph("0 &le; rho < 1; Q windows", styles["Small"]), Paragraph("Finite temporal smoothing", styles["Small"])],
        [Paragraph("Output", styles["Small"]), Paragraph("Y&#770;<sub>in</sub>, Y&#770;<sub>out</sub>, e<sub>q</sub>", styles["Small"]), Paragraph("Signal, noise monitor and residual", styles["Small"])],
    ]
    table = Table(characteristics, colWidths=[1.4 * inch, 2.1 * inch, 3.15 * inch])
    table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#202c39")), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#9aa4ad")), ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f3f5f6")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 6), ("RIGHTPADDING", (0, 0), (-1, -1), 6), ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5)]))
    story.extend([Spacer(1, 8), table, Paragraph("5. Limitations and conclusion", styles["Heading2"]), Paragraph("This preprint describes a reduced-order realtime algorithm. It does not demonstrate a physical quantum processor, a certified NVQLink deployment, or clinical benefit. A complete evaluation would require calibrated sensor geometry, Maxwell-consistent head modeling, environmental recordings, timing instrumentation, numerical conditioning studies and held-out patient data. Within those limits, finite SSS bases and explicit window updates provide a reproducible scaffold for testing low-latency MEG denoising.", styles["BodyJustified"])])

    doc.build(story)
    print(f"Generated PDF: {filename}")
    return filename


if __name__ == "__main__":
    build_pdf()