class STLGenerator:
        """
    A pure Python class to generate 3D STL models without external dependencies.
    """
            def __init__(self):
                        self.triangles = []

                            def add_triangle(self, v1, v2, v3):
                                        """Adds a triangle (normal calculation is simplified)"""
                                                # Calculate normal vector (cross product)
                                                        ux, uy, uz = v2[0]-v1[0], v2[1]-v1[1], v2[2]-v1[2]
                                                                vx, vy, vz = v3[0]-v1[0], v3[1]-v1[1], v3[2]-v1[2]
                                                                        nx = uy*vz - uz*vy
                                                                                ny = uz*vx - ux*vz
                                                                                        nz = ux*vy - uy*vx
                                                                                                # Normalize
                                                                                                        l = math.sqrt(nx*nx + ny*ny + nz*nz)
                                                                                                                if l == 0: l = 1
                                                                                                                        normal = (nx/l, ny/l, nz/l)
                                                                                                                                self.triangles.append((normal, v1, v2, v3))

                                                                                                                                    def add_cylinder(self, p1, p2, radius, segments=32):
                                                                                                                                                """Generates a cylinder between p1 and p2."""
                                                                                                                                                        dx, dy, dz = p2[0]-p1[0], p2[1]-p1[1], p2[2]-p1[2]
                                                                                                                                                                height = math.sqrt(dx*dx + dy*dy + dz*dz)
                                                                                                                                                                        if height == 0: return

                                                                                                                                                                                # Basis vectors for the circle
                                                                                                                                                                                        # Arbitrary vector not parallel to axis
                                                                                                                                                                                                ax = dx + 1 if dx == 0 else dx
                                                                                                                                                                                                        ay = dy
                                                                                                                                                                                                                az = dz
                                                                                                                                                                                                                        # Cross product to get perpendicular vector
                                                                                                                                                                                                                                px = dy*az - dz*ay
                                                                                                                                                                                                                                        py = dz*ax - dx*az
                                                                                                                                                                                                                                                pz = dx*ay - dy*ax
                                                                                                                                                                                                                                                        # Normalize
                                                                                                                                                                                                                                                                pl = math.sqrt(px*px + py*py + pz*pz)
                                                                                                                                                                                                                                                                        u = (px/pl, py/pl, pz/pl)

                                                                                                                                                                                                                                                                                # Second basis vector (cross axis and u)
                                                                                                                                                                                                                                                                                        vx = dy*u[2] - dz*u[1]
                                                                                                                                                                                                                                                                                                vy = dz*u[0] - dx*u[2]
                                                                                                                                                                                                                                                                                                        vz = dx*u[1] - dy*u[0]
                                                                                                                                                                                                                                                                                                                # Normalize
                                                                                                                                                                                                                                                                                                                        vl = math.sqrt(vx*vx + vy*vy + vz*vz)
                                                                                                                                                                                                                                                                                                                                v = (vx/vl, vy/vl, vz/vl)

                                                                                                                                                                                                                                                                                                                                        # Generate points
                                                                                                                                                                                                                                                                                                                                                points1 = []
                                                                                                                                                                                                                                                                                                                                                        points2 = []
                                                                                                                                                                                                                                                                                                                                                                for i in range(segments + 1):
                                                                                                                                                                                                                                                                                                                                                                                angle = 2 * math.pi * i / segments
                                                                                                                                                                                                                                                                                                                                                                                            c = math.cos(angle) * radius
                                                                                                                                                                                                                                                                                                                                                                                                        s = math.sin(angle) * radius

                                                                                                                                                                                                                                                                                                                                                                                                                    # Point on bottom circle
                                                                                                                                                                                                                                                                                                                                                                                                                                pt1 = (p1[0] + c*u[0] + s*v[0],
                                                                                                                                                                                                                                                                                                                                                                                                                                                          p1[1] + c*u[1] + s*v[1],
                                                                                                                                                                                                                                                                                                                                                                                                                                                          p1[2] + c*u[2] + s*v[2])

                                                                                                                                                                                                                                                                                                                                                                                                                                            # Point on top circle
                                                                                                                                                                                                                                                                                                                                                                                                                                                        pt2 = (p2[0] + c*u[0] + s*v[0],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  p2[1] + c*u[1] + s*v[1],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  p2[2] + c*u[2] + s*v[2])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    points1.append(pt1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                points2.append(pt2)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Create faces (side walls)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for i in range(segments):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.add_triangle(points1[i], points2[i], points1[i+1])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.add_triangle(points2[i], points2[i+1], points1[i+1])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # End caps
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            center1 = p1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    center2 = p2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for i in range(segments):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.add_triangle(center1, points1[i+1], points1[i]) # Bottom cap
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.add_triangle(center2, points2[i], points2[i+1]) # Top cap

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def save_stl(self, filename, object_name="object"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Writes the mesh to an ASCII STL file."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"Generating {filename}...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with open(filename, 'w') as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f.write(f"solid {object_name}\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for normal, v1, v2, v3 in self.triangles:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f.write(f"  facet normal {normal[0]:.4f} {normal[1]:.4f} {normal[2]:.4f}\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f.write("    outer loop\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f.write(f"      vertex {v1[0]:.4f} {v1[1]:.4f} {v1[2]:.4f}\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f.write(f"      vertex {v2[0]:.4f} {v2[1]:.4f} {v2[2]:.4f}\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f.write(f"      vertex {v3[0]:.4f} {v3[1]:.4f} {v3[2]:.4f}\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f.write("    endloop\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f.write("  endfacet\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f.write(f"endsolid {object_name}\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Success! Saved {len(self.triangles)} polygons to {filename}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # --- Design Execution ---

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def generate_pipeline_design():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cad = STLGenerator()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # DESIGN SPECS: Trans Mountain Expansion (TMX)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Diameter: 36 inches (approx 914mm). We use meters as units.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pipe_radius = 0.914 / 2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    length = 10.0 # 10 meter segment

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # 1. Main Pipe Body
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cad.add_cylinder((0,0,0), (length,0,0), pipe_radius)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # 2. ANSI Flange Connection (Left Side)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Flanges are typically larger diameter (approx 1.5x pipe)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flange_width = 0.3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            flange_radius = pipe_radius * 1.6
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cad.add_cylinder((0.5,0,0), (0.5+flange_width, 0, 0), flange_radius)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # 3. Weld Neck (connecting flange to pipe)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cad.add_cylinder((0.5+flange_width, 0,0), (1.0, 0,0), pipe_radius * 1.1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cad.save_stl("AB_BC_Pipeline_Segment.stl", "Pipeline_36in_TMX")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def generate_refinery_tank_design():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cad = STLGenerator()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # DESIGN SPECS: Standard Crude Oil Storage Tank
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Diameter: 50 meters, Height: 20 meters
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tank_radius = 25.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tank_height = 20.0

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # 1. Main Tank Shell (Cylinder)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cad.add_cylinder((0,0,0), (0,0,tank_height), tank_radius, segments=64)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # 2. Floating Roof (Slightly smaller cylinder inside)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Positioned at 70% capacity
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        roof_height = 0.5
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            liquid_level = tank_height * 0.7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cad.add_cylinder((0,0,liquid_level), (0,0,liquid_level+roof_height), tank_radius * 0.98, segments=64)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # 3. Wind Girder / Stiffening Ring (Near top)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cad.add_cylinder((0,0,tank_height-1), (0,0,tank_height-0.8), tank_radius * 1.02, segments=64)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cad.save_stl("Burnaby_Refinery_Tank.stl", "Crude_Tank_50m")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    generate_pipeline_design()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        generate_refinery_tank_design()~
