
import os
import json
import numpy as np

class FEAEngine:
    def __init__(self, output_dir="backend/data"):
        self.output_dir = output_dir
        
    def run_analysis(self, implant_geometry, material_props):
        """
        Simulates Von Mises stress analysis on the implant.
        """
        vertices = np.array(implant_geometry['vertices'])
        
        # Fake stress calculation based on z-height (leverage effect)
        z_coords = vertices[:, 2]
        stress_mises = z_coords * 50.0 * material_props.get('modulus', 200) / 1000.0
        
        # Attach to geometry for frontend visualization
        implant_geometry['stress_values'] = stress_mises.tolist()
        
        results = {
            "max_stress": float(np.max(stress_mises)),
            "min_stress": float(np.min(stress_mises)),
            "deformation": float(np.mean(stress_mises) * 0.001),
            "safety_factor": float(250.0 / (np.max(stress_mises) + 1e-5))
        }
        
        return results, stress_mises

    def export_ansys(self, filename, geometry, stress_data):
        """
        Writes an ANSYS APDL-like script or compatible data file.
        """
        filepath = os.path.join(self.output_dir, "ansys", filename)
        with open(filepath, 'w') as f:
            f.write("! ANSYS APDL BATCH FILE GENERATED BY NVQLINK FEA ENGINE\n")
            f.write("/PREP7\n")
            f.write("! Geometry Definitions\n")
            for i, v in enumerate(geometry['vertices']):
                f.write(f"K,{i+1},{v[0]:.4f},{v[1]:.4f},{v[2]:.4f}\n")
            
            f.write("\n! Material Properties\n")
            f.write("MP,EX,1,200E9\n")
            f.write("MP,PRXY,1,0.3\n")
            
            f.write("\n! Results Data (Commented)\n")
            f.write(f"! Max Stress: {np.max(stress_data):.2f} MPa\n")
            f.write("/SOL\n")
            f.write("SOLVE\n")
            f.write("FINISH\n")
            
        print(f"ANSYS file written to {filepath}")
        return filepath

    def export_design_session(self, filename, session_data):
        filepath = os.path.join(self.output_dir, "sessions", filename)
        with open(filepath, 'w') as f:
            json.dump(session_data, f, indent=4)
        print(f"Session file written to {filepath}")
        return filepath

    def export_implant_design(self, filename, geometry):
        filepath = os.path.join(self.output_dir, "implant_design", filename)
        with open(filepath, 'w') as f:
            json.dump(geometry, f, indent=4)
        print(f"Implant design written to {filepath}")
        return filepath

    def generate_stress_strain_lut(self, material_name):
        """
        Generates a Stress-Strain Lookup Table (LUT) for a given material.
        Simulates Elastic and Plastic deformation regions.
        """
        materials = {
            "Titanium": {"E": 110, "Yield": 880, "Ultimate": 950, "MaxStrain": 0.15},
            "Zirconia": {"E": 210, "Yield": 1200, "Ultimate": 1400, "MaxStrain": 0.05} # Brittle, higher modulus
        }
        
        props = materials.get(material_name, materials["Titanium"])
        E = props["E"] * 1000 # Convert GPa to MPa
        yield_stress = props["Yield"]
        
        lut = []
        steps = 50
        max_strain = props["MaxStrain"]
        
        for i in range(steps + 1):
            strain = (i / steps) * max_strain
            
            # Elastic Region
            yield_strain = yield_stress / E
            
            if strain <= yield_strain:
                stress = strain * E
            else:
                # Simplified Plastic Region (Power Law / Hardening)
                # Sigma = K * epsilon^n + Sigma_y
                plastic_strain = strain - yield_strain
                hardening = 500 * (plastic_strain ** 0.5) 
                stress = yield_stress + hardening
                
                if stress > props["Ultimate"]:
                    stress = props["Ultimate"]
            
            lut.append({
                "strain": float(strain),
                "stress": float(stress),
                "region": "elastic" if strain <= yield_strain else "plastic"
            })
            
        return lut

    def export_lut(self, filename, lut_data):
        lut_dir = os.path.join(self.output_dir, "lookup_tables")
        os.makedirs(lut_dir, exist_ok=True)
        filepath = os.path.join(lut_dir, filename)
        with open(filepath, 'w') as f:
            json.dump(lut_data, f, indent=4)
        print(f"LUT written to {filepath}")
        return filepath
