
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os

def create_summary_dashboard():
    print("Generating Final Visual Summary Dashboard...")
    
    # Files to include
    files = {
        'Whole Brain Dual Encoding': 'whole_brain_dual_encoding.png', # The main result
        'Synaptic Comp': 'post_synaptic_treatment_plot.png',
        '2D Projections': '2d_projections_hebbian.png',
        'Repaired 3D State': '3d_projection_prime_resonance_repaired.png'
    }
    
    # Filter for existing files
    valid_files = {k: v for k, v in files.items() if os.path.exists(v)}
    
    if not valid_files:
        print("No image files found to summarize!")
        return

    n_images = len(valid_files)
    cols = 2
    rows = (n_images + 1) // 2
    
    fig = plt.figure(figsize=(16, 8 * rows))
    fig.suptitle("Quantum Neural Restoration: Final Summary Dashboard", fontsize=24, fontweight='bold', y=0.98)
    
    for i, (title, filename) in enumerate(valid_files.items()):
        ax = fig.add_subplot(rows, cols, i+1)
        try:
            img = mpimg.imread(filename)
            ax.imshow(img)
            ax.set_title(f"{title} ({filename})", fontsize=14, pad=10)
            ax.axis('off')
            # Add a border
            for spine in ax.spines.values():
                spine.set_visible(True)
                spine.set_edgecolor('#ccc')
        except Exception as e:
            ax.text(0.5, 0.5, f"Error loading {filename}", ha='center')
            
    plt.tight_layout()
    # Add a footer
    plt.figtext(0.5, 0.01, "Generated by Neuromorph Agentic Cluster - 2025", ha='center', fontsize=10, color='gray')
    
    output_filename = "Final_Visual_Summary.png"
    plt.savefig(output_filename, dpi=150, facecolor='#f8f9fa')
    print(f"Summary Dashboard saved to {output_filename}")

if __name__ == "__main__":
    create_summary_dashboard()
