"""
Moduli-Theoretic Optimal Treatment Paradigm for rTMS.

Treats the (frequency, intensity) stimulation-parameter plane as the upper
half-plane H, acted on by the modular group SL(2,Z) via Mobius transformations.
Reduces each candidate protocol to the standard fundamental domain

    F = { z in H : |Re(z)| <= 1/2, |z| >= 1 }

using the classical Gauss/Euclidean reduction algorithm (the same recursive
structure as continued-fraction expansion). Protocols whose reduced point
lands near one of the two elliptic points of F -- z = i (order-2 stabilizer,
generated by S: z -> -1/z) or z = rho = exp(i*pi/3) (order-3 stabilizer,
generated by ST) -- possess an enlarged stabilizer subgroup and are treated
as "modular resonance points": stimulation protocols with maximal robustness
to small parameter drift.

The optimal reduced protocol drives a boundary-element (single-layer
potential) simulation of the induced cortical-surface field from a magnetic
dipole coil, producing 2D heat maps for both the moduli-stability surface and
the cortical potential field.
"""

import cmath
import math

import numpy as np


# ── Modular group reduction (SL(2,Z) fundamental domain algorithm) ─────────

def _divisor_sum(n, k):
    return sum(d ** k for d in range(1, n + 1) if n % d == 0)


def _reduce_to_fundamental_domain(z, max_iter=60):
    """Gauss/Euclidean reduction of z into F = {|Re|<=1/2, |z|>=1}, Im(z) > 0."""
    path = []
    for _ in range(max_iter):
        shift = round(z.real)
        if shift != 0:
            z = complex(z.real - shift, z.imag)
            path.append({'op': 'T', 'n': -shift})
        if abs(z) >= 1.0 - 1e-12:
            break
        z = complex(-1.0, 0.0) / z if z != 0 else complex(0.0, 1.0)
        # Mobius inversion S: z -> -1/z
        path.append({'op': 'S'})
    return z, path


def _j_invariant(z, n_terms=10):
    """Truncated q-expansion of the classical elliptic modular j-invariant at z (Im z >= sqrt(3)/2)."""
    q = cmath.exp(2j * cmath.pi * z)
    e4 = 1.0 + 0.0j
    e6 = 1.0 + 0.0j
    qn = 1.0 + 0.0j
    for n in range(1, n_terms + 1):
        qn *= q
        e4 += 240.0 * _divisor_sum(n, 3) * qn
        e6 -= 504.0 * _divisor_sum(n, 5) * qn
    denom = (e4 ** 3 - e6 ** 2)
    if abs(denom) < 1e-30:
        return complex(0.0, 0.0)
    return 1728.0 * (e4 ** 3) / denom


def _stability_score(z_reduced):
    """Proximity of the reduced point to the two elliptic points i and rho = e^{i*pi/3}."""
    elliptic_i = complex(0.0, 1.0)
    elliptic_rho = cmath.exp(1j * cmath.pi / 3.0)
    d_i = abs(z_reduced - elliptic_i)
    d_rho = abs(z_reduced - elliptic_rho)
    d_min = min(d_i, d_rho)
    nearest = 'i (order-2 elliptic point)' if d_i <= d_rho else 'rho (order-3 elliptic point)'
    return float(np.exp(-4.0 * d_min ** 2)), nearest, float(d_min)


def simulate_moduli_reduction(freq_hz, intensity_pct):
    """Reduce a single (frequency, intensity) protocol into the SL(2,Z) fundamental domain."""
    z = complex(float(freq_hz), max(0.05, float(intensity_pct) / 100.0))
    z_reduced, path = _reduce_to_fundamental_domain(z)
    stability, nearest, dist = _stability_score(z_reduced)
    j_val = _j_invariant(z_reduced if z_reduced.imag >= 0.6 else complex(z_reduced.real, 0.87))
    return {
        'z_original': {'re': round(z.real, 4), 'im': round(z.imag, 4)},
        'z_reduced': {'re': round(z_reduced.real, 4), 'im': round(z_reduced.imag, 4)},
        'reduction_path': path,
        'stability_score': round(stability, 6),
        'nearest_elliptic_point': nearest,
        'elliptic_distance': round(dist, 6),
        'j_invariant': {'re': round(j_val.real, 3), 'im': round(j_val.imag, 3)},
    }


def _moduli_stability_grid(freq_range=(1.0, 50.0), intensity_range=(10.0, 150.0), resolution=46):
    """Full 2D moduli-stability heat map over the (frequency, intensity) protocol plane."""
    freqs = np.linspace(freq_range[0], freq_range[1], resolution)
    intensities = np.linspace(intensity_range[0], intensity_range[1], resolution)
    stability_grid = np.zeros((resolution, resolution))

    best = {'stability': -1.0, 'freq': freqs[0], 'intensity': intensities[0]}
    for i, inten in enumerate(intensities):
        for j, f in enumerate(freqs):
            z = complex(float(f), float(inten) / 100.0)
            z_reduced, _ = _reduce_to_fundamental_domain(z)
            stability, _, _ = _stability_score(z_reduced)
            stability_grid[i, j] = stability
            if stability > best['stability']:
                best = {'stability': stability, 'freq': float(f), 'intensity': float(inten)}

    return {
        'freq_axis': [round(float(f), 3) for f in freqs],
        'intensity_axis': [round(float(v), 3) for v in intensities],
        'stability': stability_grid.round(5).tolist(),
        'argmax': best,
    }


# ── Boundary Element single-layer potential (magnetic dipole coil source) ──

def _bem_cortical_heatmap(intensity_pct, resolution=48, coil_height=1.35):
    """
    Single-layer boundary-element potential induced on a deformed-sphere cortical
    surface by a magnetic dipole coil positioned above the scalp:

        phi(x) = (mu0 / 4*pi) * m . (x - x_coil) / |x - x_coil|^3

    discretized over the boundary mesh (theta, phi) of the cortical surface.
    """
    mu0 = 4.0 * np.pi * 1e-7
    moment = (intensity_pct / 100.0) * 2.0  # dipole moment scaled by coil drive intensity

    theta = np.linspace(0.0, 2.0 * np.pi, resolution)
    phi = np.linspace(0.02, np.pi - 0.02, resolution // 2)
    TH, PH = np.meshgrid(theta, phi)

    r_surface = 1.0 + 0.05 * np.sin(5 * TH) * np.cos(4 * PH)
    X = r_surface * np.sin(PH) * np.cos(TH)
    Y = r_surface * np.sin(PH) * np.sin(TH)
    Z = r_surface * np.cos(PH)

    coil_pos = np.array([0.0, 0.0, coil_height])
    dx, dy, dz = X - coil_pos[0], Y - coil_pos[1], Z - coil_pos[2]
    dist3 = (dx ** 2 + dy ** 2 + dz ** 2) ** 1.5
    dist3 = np.maximum(dist3, 1e-6)
    potential = (mu0 / (4.0 * np.pi)) * moment * dz / dist3
    potential_scaled = potential * 1e7  # rescale to a convenient display range

    return {
        'theta': [round(float(t), 4) for t in theta],
        'phi': [round(float(p), 4) for p in phi],
        'potential': potential_scaled.round(4).tolist(),
        'x': X.round(4).tolist(),
        'y': Y.round(4).tolist(),
        'z': Z.round(4).tolist(),
        'peak_potential': round(float(np.max(np.abs(potential_scaled))), 4),
    }


def _bem_depth_attenuation(intensity_pct, n_points=50):
    """Layered-conductivity field attenuation with cortical depth, driven by the optimal intensity."""
    conductivities = {'Scalp': 0.33, 'Skull': 0.0042, 'CSF': 1.79, 'Grey Matter': 0.33}
    boundaries = [0.0, 0.06, 0.12, 0.20]
    depths = np.linspace(0.0, 1.0, n_points)
    e0 = intensity_pct

    field = []
    for d in depths:
        v = e0
        for (name, sigma), boundary in zip(conductivities.items(), boundaries):
            if d >= boundary:
                v *= math.exp(-sigma * (d - boundary) * 4.0)
        field.append(round(float(v), 3))

    return {
        'depths_mm': [round(float(d * 45.0), 2) for d in depths],
        'field_pct': field,
    }


def get_moduli_bem_paradigm(condition='stroke', freq_range=(1.0, 50.0), intensity_range=(10.0, 150.0)):
    """
    Master entry point: moduli-theoretic stability heat map, the argmax-stability
    optimal protocol, its SL(2,Z) reduction path, boundary-element cortical
    potential heat map at that protocol, depth attenuation, and continued-fraction
    convergents of the optimal frequency (linking the reduction algorithm's
    Euclidean structure back to the existing rTMS frequency-synchronization model).
    """
    try:
        from .rtms_engine import _continued_fraction_convergents
    except ImportError:
        from logic.rtms_engine import _continued_fraction_convergents

    grid = _moduli_stability_grid(freq_range, intensity_range)
    optimal_freq = grid['argmax']['freq']
    optimal_intensity = grid['argmax']['intensity']

    reduction = simulate_moduli_reduction(optimal_freq, optimal_intensity)
    bem_heatmap = _bem_cortical_heatmap(optimal_intensity)
    attenuation = _bem_depth_attenuation(optimal_intensity)
    cf_convergents = _continued_fraction_convergents(optimal_freq, depth=8)

    condition_labels = {
        'stroke': 'Stroke Motor Rehabilitation', 'dementia': 'Dementia Cognitive Enhancement',
        'tremor': 'Essential Tremor', 'ocd': 'OCD Deep Circuit Modulation',
    }
    label = condition_labels.get(condition, condition.capitalize())

    ascii_schematic = (
        "               ===================================================================\n"
        "               MODULI-THEORETIC OPTIMAL TREATMENT PARADIGM (SL(2,Z) x BEM)\n"
        "               ===================================================================\n\n"
        f"               CONDITION: {label}\n\n"
        "               +---------------------------+          +----------------------------+\n"
        "               | SL(2,Z) FUNDAMENTAL DOMAIN|          | BOUNDARY ELEMENT SINGLE-   |\n"
        "               |  REDUCTION  z -> F         |          | LAYER POTENTIAL SOLVER     |\n"
        "               +-------------+-------------+          +--------------+-------------+\n"
        "                             |                                       |\n"
        "                             v                                       v\n"
        f"               [Optimal f* = {optimal_freq:.2f} Hz, I* = {optimal_intensity:.1f}% MSO]      [Peak Cortical Potential: {bem_heatmap['peak_potential']:.2f}]\n"
        f"               [Reduced z* = {reduction['z_reduced']['re']:.3f} + {reduction['z_reduced']['im']:.3f}i]        [Nearest Elliptic Point: {reduction['nearest_elliptic_point']}]\n"
        "                             |                                       |\n"
        "                             +=========( Stability Score )==========+\n"
        f"                                   Phi(z*) = {reduction['stability_score']:.4f}\n"
        "                                             |\n"
        "                                             v\n"
        "               +-------------------------------------------------------------------+\n"
        f"               |   Continued-Fraction Frequency Convergents: {', '.join(str(c['numerator']) + '/' + str(c['denominator']) for c in cf_convergents[:4])}\n"
        "               +-------------------------------------------------------------------+\n"
    )

    clinical_summary = (
        f"**Moduli-Theoretic Optimal Treatment Paradigm Report ({label}):**\n\n"
        f"1. **Modular Reduction**: The candidate protocol plane (frequency, intensity) is treated as the upper half-plane $\\mathbb{{H}}$ "
        f"under the SL(2,Z) modular group action. The stability-maximizing protocol at **{optimal_freq:.2f} Hz / {optimal_intensity:.1f}% MSO** "
        f"reduces via the Gauss algorithm to $z^* = {reduction['z_reduced']['re']:.3f} + {reduction['z_reduced']['im']:.3f}i$ inside the standard "
        f"fundamental domain, lying closest to the **{reduction['nearest_elliptic_point']}** (distance {reduction['elliptic_distance']:.4f}), "
        f"the point of maximal symmetry (largest stabilizer subgroup) in the modular curve.\n\n"
        f"2. **Stability Score**: $\\Phi(z^*) = {reduction['stability_score']:.4f}$, indicating strong robustness of this protocol to small "
        f"frequency/intensity perturbations, since nearby elliptic points anchor locally flat regions of the modular-invariant response surface.\n\n"
        f"3. **Boundary Element Cortical Field**: At the optimal intensity, the single-layer boundary-element potential solver predicts a peak "
        f"induced cortical surface potential of **{bem_heatmap['peak_potential']:.2f}** (scaled units) directly beneath the coil, with layered "
        f"scalp/skull/CSF/grey-matter conductivity attenuation reducing the field to **{attenuation['field_pct'][-1]:.1f}%** of surface intensity "
        f"at maximal modeled cortical depth.\n\n"
        f"4. **Continued-Fraction Synchronization**: The optimal frequency's continued-fraction convergents "
        f"[{', '.join(str(c['numerator']) + '/' + str(c['denominator']) for c in cf_convergents[:5])}] provide rational sub-harmonic pulse-timing "
        f"ratios for phase-locked multi-coil delivery, directly reusing the platform's existing frequency-synchronization engine."
    )

    return {
        'condition': condition,
        'label': label,
        'moduli_grid': grid,
        'optimal_protocol': {
            'frequency_hz': round(optimal_freq, 3),
            'intensity_pct': round(optimal_intensity, 2),
            **reduction,
        },
        'bem_heatmap': bem_heatmap,
        'bem_attenuation': attenuation,
        'cf_convergents': cf_convergents,
        'ascii_schematic': ascii_schematic,
        'clinical_summary': clinical_summary,
    }
